// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: acl-config.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config stores ACL configuration parameters.
type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// CCName - ACL chaincode name
	CCName string `protobuf:"bytes,1,opt,name=CCName,proto3" json:"CCName,omitempty"`
	// adminSKI - ACL admin public key SKI in hex format
	AdminSKI []byte `protobuf:"bytes,2,opt,name=adminSKI,proto3" json:"adminSKI,omitempty"`
	// validatorsCount - set of validators public keys length
	ValidatorsCount int64 `protobuf:"varint,3,opt,name=validatorsCount,proto3" json:"validatorsCount,omitempty"`
	// validators - set of validators public keys
	Validators []string `protobuf:"bytes,4,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acl_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_acl_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_acl_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetCCName() string {
	if x != nil {
		return x.CCName
	}
	return ""
}

func (x *Config) GetAdminSKI() []byte {
	if x != nil {
		return x.AdminSKI
	}
	return nil
}

func (x *Config) GetValidatorsCount() int64 {
	if x != nil {
		return x.ValidatorsCount
	}
	return 0
}

func (x *Config) GetValidators() []string {
	if x != nil {
		return x.Validators
	}
	return nil
}

var File_acl_config_proto protoreflect.FileDescriptor

var file_acl_config_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x63, 0x6c, 0x2d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xc1, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3d, 0x0a,
	0x06, 0x43, 0x43, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x25, 0xfa,
	0x42, 0x22, 0x72, 0x20, 0x32, 0x1e, 0x5e, 0x5b, 0x41, 0x2d, 0x5a, 0x5d, 0x2b, 0x5b, 0x41, 0x2d,
	0x5a, 0x30, 0x2d, 0x39, 0x5d, 0x2b, 0x28, 0x2d, 0x5b, 0x41, 0x2d, 0x5a, 0x30, 0x2d, 0x39, 0x5d,
	0x2b, 0x29, 0x3f, 0x24, 0x52, 0x06, 0x43, 0x43, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x08,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x4b, 0x49, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x12,
	0xfa, 0x42, 0x0f, 0x72, 0x0d, 0x32, 0x0b, 0x5e, 0x5b, 0x30, 0x2d, 0x39, 0x61, 0x2d, 0x66, 0x5d,
	0x2b, 0x24, 0x52, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x4b, 0x49, 0x12, 0x28, 0x0a, 0x0f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_acl_config_proto_rawDescOnce sync.Once
	file_acl_config_proto_rawDescData = file_acl_config_proto_rawDesc
)

func file_acl_config_proto_rawDescGZIP() []byte {
	file_acl_config_proto_rawDescOnce.Do(func() {
		file_acl_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_acl_config_proto_rawDescData)
	})
	return file_acl_config_proto_rawDescData
}

var file_acl_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_acl_config_proto_goTypes = []interface{}{
	(*Config)(nil), // 0: proto.Config
}
var file_acl_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_acl_config_proto_init() }
func file_acl_config_proto_init() {
	if File_acl_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_acl_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_acl_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acl_config_proto_goTypes,
		DependencyIndexes: file_acl_config_proto_depIdxs,
		MessageInfos:      file_acl_config_proto_msgTypes,
	}.Build()
	File_acl_config_proto = out.File
	file_acl_config_proto_rawDesc = nil
	file_acl_config_proto_goTypes = nil
	file_acl_config_proto_depIdxs = nil
}
