name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: atomyze-foundation/workflows/.github/workflows/validate--v1.yml@main

  go-qa-l0:
    needs:
      - validate
    uses: atomyze-foundation/workflows/.github/workflows/go-validate--v1.yml@main
    secrets: inherit

  go-qa-l1:
    needs:
      - go-qa-l0
    uses: atomyze-foundation/workflows/.github/workflows/go-lint--v1.yml@main

  go-qa-l2:
    needs:
      - go-qa-l1
    uses: atomyze-foundation/workflows/.github/workflows/go-test--v1.yml@main
    secrets: inherit

  go-qa-l3:
    needs:
      - go-qa-l2
    uses: atomyze-foundation/workflows/.github/workflows/go-static--v1.yml@main
    secrets: inherit
  
  build-chaincode:
    needs:
      - go-qa-l3
    strategy:
      matrix:
        HLF_VERSION:
          - 2.4
          - 2.5
    uses: atomyze-foundation/workflows/.github/workflows/go-chaincode--v1.yml@main
    secrets: inherit
    with:
      HLF_VERSION: ${{ matrix.HLF_VERSION }}
